### PR TITLE
Disable restrict keyword, this fails with the default CC on circleci.

### PR DESCRIPTION
**Pull request by mberhault**

### CODE REVIEW

**Comment by petermattis** [comment]
LGTM

**Comment by tbg** [comment]
Is this going to break when we update jemalloc and the file gets
overwritten? If so, document.

On Thu, Apr 28, 2016 at 9:38 AM marc notifications@github.com wrote:

> Merged #3 https://github.com/cockroachdb/c-jemalloc/pull/3.
> 
> —
> You are receiving this because you were assigned.
> 
> Reply to this email directly or view it on GitHub
> https://github.com/cockroachdb/c-jemalloc/pull/3#event-644313708
> 
> ## 

-- Tobias

**Comment by mberhault** [comment]
the thing is, someone needs to run `./configure`, but this is going to be different based on the build chain they use. Not quite sure what the best solution is. I'll document for now, new PR coming up.

**Comment by bdarnell** [comment]
When do we build with the default cc on circleci? I thought we did everything in the builder docker image, which has newer compilers.

**Comment by mberhault** [comment]
possibly, I didn't dig far enough into it. all I know is that the restrict keyword doesn't exist.

**Comment by mberhault** [comment]
meh:
```
$ cat /sys/fs/cgroup/memory/memory.limit_in_bytes
9223372036854771712
```

I'll fix it.

**Comment by mberhault** [comment]
sorry, wrong place for the previous comment, removing.

**Comment by mberhault** [comment]
fixed in https://github.com/cockroachdb/c-jemalloc/pull/4, thanks @tamird

**Pull request merged**
