### PR TITLE
Update upstream to 4.5.0

### PR DESCRIPTION
**Pull request by tamird**
This claims to fix a bunch of regressions: https://github.com/jemalloc/jemalloc/releases/tag/4.5.0.

@knz can you do the freebsd stuff?

### CODE REVIEW

**Comment by knz** [comment]
done

**Comment by knz** [comment]
I note that you removed `-O3 -funroll-loops`. Was there a reason? I surmise it would make a performance difference.

**Comment by tamird** [comment]
Yeah, it might; I'll do some testing before merging this.

**Comment by petermattis** [comment]
Do you know if any of those bug fixes affect us? Channel my inner @bdarnell, we should be extra cautious about updating libs at this point in the dev cycle.

**Comment by tamird** [comment]
Haven't a clue!

**Comment by tamird** [comment]
@knz the performance difference is in the noise -- Go already passes -O2, and the difference between O2 and O3 is not always clear (O3 can yield worse performance in some cases).

@bdarnell care to weigh in?

**Comment by bdarnell** [comment]
I'm not thrilled with an upgrade like this when we don't have any evidence that we're affected by any bugs in the current version, but I'm not overly concerned about this particular release - jemalloc has a good track record and this release was focused on testing and bug fixes.

**Comment by tamird** [comment]
Is that an LGTM?

**Comment by tamird** [comment]
@bdarnell looks like we might want this after all. https://github.com/jemalloc/jemalloc/compare/4.4.0...4.5.0 notably includes https://github.com/jemalloc/jemalloc/pull/561.

**Comment by tamird** [comment]
We might not be affected by that yet, but if we start to hit one of the affected paths we'll just crash on OS X.

**Comment by bdarnell** [comment]
LGTM

**Pull request merged**
