### PR TITLE
Make c-jemalloc compile on FreeBSD.

### PR DESCRIPTION
**Pull request by knz**

### CODE REVIEW

**Comment by mberhault** [comment]
you probably want to run `./configure` with `--enable-prof` (it defines `JEMALLOC_PROF` which is off in this PR).
You may also want to adjust `import.sh` with instructions for FreeBSD.

**Comment by knz** [comment]
Done.

**Comment by mberhault** [comment]
LGTM.

After changing the `cockroachdb/cockroach` flags (`cmd/start_jemalloc.go` and `server/status/runtime_jemalloc.go`), you'll see if it works properly just by running it. We output jemalloc stats at the same time at the runtime stats.
Setting the  `COCKROACH_MEMPROF_INTERVAL=10s` env variable will also dump two profiles (`memprof` and `jeprof` for go and cgo respectively) do `<logs-dir>`.

**Comment by knz** [comment]
Yep, it works.

**Pull request merged**
