### PR TITLE
Update upstream to 4.3.1

### PR DESCRIPTION
**Pull request by tamird**
Note that the freebsd_includes haven't been updated here because I don't have access to a FreeBSD machine.

@knz if you'd like to help out here, check out this branch and run:
```sh
./import.sh
(cd internal && ./configure --enable-prof)
rm -r freebsd_includes
git clean -Xn -- internal/include/jemalloc | sed 's/.* //' | xargs -I % rsync -R % freebsd_includes/
git add freebsd_includes
git commit -m 'freebsd includes'
git clean -dxf
go build ./... # confirm it builds
git push
```

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/c-jemalloc/7)

### CODE REVIEW

**Comment by knz** [comment]
hold on, testing now

**Comment by knz** [comment]
For future reference the instructions should read:

```
MAKE=gmake bash ./import.sh
(cd internal && bash autogen.sh && ./configure --enable-prof)
rm -r freebsd_includes
git clean -Xn -- internal/include/jemalloc | sed 's/.* //' | xargs -I % rsync -R % freebsd_includes/
git add freebsd_includes
git commit -m 'freebsd includes'
git clean -dxf
go build ./... # confirm it builds
git push
```

Also I'm getting the following, but I think it's innocuous:

```
# _/home/kena/src/c-jemalloc
cc: warning: argument unused during compilation: '-gno-record-gcc-switches'
# _/home/kena/src/c-jemalloc
cc: warning: argument unused during compilation: '-pthread'
cc: warning: argument unused during compilation: '-gno-record-gcc-switches'
```

**Comment by tamird** [comment]
wait, why did you need to autogen? That shouldn't be necessary on a released tarball.

**Comment by knz** [comment]
You just asked me to check out this branch! I was working from scratch.

**Comment by tamird** [comment]
Ah, I forgot to tell you to comment out the `git clean -dxf` at the end of `import.sh`!

**Comment by knz** [comment]
ah :) So should I re-do without the git clean?

**Comment by tamird** [comment]
Yep!

**Comment by knz** [comment]
done.

**Comment by tamird** [comment]
OK, squashed. @petermattis PTAL (suggest you use reviewable https://reviewable.io/reviews/cockroachdb/c-jemalloc/7)

**Comment by petermattis** [comment]
LGTM, though let's hold off on merging until the issue with `delta` is figured out. There is no urgency to this change and yet it could have systemic effects.

**Comment by tamird** [comment]
Merging this is harmless, though I agree on holding off on picking it up
downstream.

**Comment by petermattis** [comment]
Ah, yes. Merge away, but let's not pick it up in `cockroach`.

**Pull request merged**
