### PR TITLE
OpenBSD compatibility

### PR DESCRIPTION
**Pull request by benesch**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/c-jemalloc/24)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 19 of 19 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cgo_flags.go, line 14 at r2](https://reviewable.io:443/reviews/cockroachdb/c-jemalloc/24#-Kh4dxZtcFy3JXKzYbHH:-Kh4dxZtcFy3JXKzYbHI:b-7jx6jl) ([raw file](https://github.com/cockroachdb/c-jemalloc/blob/e709c7e78609e4652b056751c2500be167805c9a/cgo_flags.go#L14)):*
> ```Go
> // #cgo linux CPPFLAGS: -Ilinux_includes/internal/include -Ilinux_includes/internal/include/jemalloc/internal
> // #cgo freebsd CPPFLAGS: -Ifreebsd_includes/internal/include -Ifreebsd_includes/internal/include/jemalloc/internal
> // #cgo openbsd CPPFLAGS: -Iopenbsd_includes/internal/include -Iopenbsd_includes/internal/include/jemalloc/internal
> ```

as discussed, let's put these in `cgo_flags_GOOS_GOARCH.go` files so that our supported architectures are explicit.

See https://github.com/cockroachdb/c-jemalloc/pull/23

---

*[import.sh, line 49 at r2](https://reviewable.io:443/reviews/cockroachdb/c-jemalloc/24#-Kh4eG6nc7kn43NsLL-Y:-Kh4eG6nc7kn43NsLL-Z:b-nttkv1) ([raw file](https://github.com/cockroachdb/c-jemalloc/blob/e709c7e78609e4652b056751c2500be167805c9a/import.sh#L49)):*
> ```Shell
> # on OpenBSD:
> # (cd internal && ./configure)
> # <compare "Build parameters" in internal/Makefile to cgo flags in cgo_flags.go> and adjust the latter.
> ```

heh this closing angle bracket is in the wrong place I think

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/c-jemalloc/24#-:-Kh4eM0j4qBt4E2EhUpp:bnfp4nl)*

**Comment by bdarnell** [comment]
LGTM, but please include notes on how to get an openbsd VM and install the necessary tools so we don't have to start from scratch for the next jemalloc update.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/c-jemalloc/24#-:-Kh4g4L_qnD25kwRFRZr:bbvwq19)*

**Review by tamird — COMMENTED** [review]
Attempting to get this off my GH dashboard.

**Comment by benesch** [comment]
How’s this?

**Pull request closed without merging**
